#ifdef __cplusplus
extern "C"
#endif

#include "pmtk.h"
#include "config.h"
#include "protein_atomic_info.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef ALLOCPAGESIZE
#define ALLOCPAGESIZE 1024
#endif

static inline void _readLineS(char *line, float coords[])
{
	//read coords
	line[54]='\0';
    coords[2]=atof(&line[46]);
	line[46]='\0';
	coords[1]=atof(&line[38]);
	line[38]='\0';
	coords[0]=atof(&line[30]);
}

static inline void _readLine(char *line, PMAtomDesc *info, float coords[])
{
	//read info
	register char *s = (char*)info;
	s[0]=line[0];
	memcpy(&s[1],&line[6],21);
	//read coords
	line[54]='\0';
    coords[2]=atof(&line[46]);
	line[46]='\0';
	coords[1]=atof(&line[38]);
	line[38]='\0';
	coords[0]=atof(&line[30]);
}



static float *pmFReadPDBFrameFull(FILE* stream,PMAtomDesc** atominfo,size_t *atoms)
{
	size_t i=0;
	char linebuffer[128];

	float *coords=0, *c;
	PMAtomDesc *info=0, *a;

	size_t alloc = ALLOCPAGESIZE;

	//check if size is known
	if(*atoms)
		alloc = *atoms;

	while(fgets(linebuffer,128,stream)){
	        //fprintf(stderr,"%i[%i]\n",i,(i%alloc));
		//only atom lines
		if(!strncmp(linebuffer,"ATOM",4) || !strncmp(linebuffer,"HETATM",6)){
			//test line
	        if(strlen(linebuffer)<54)break; // underfull line

	        //allocate more memory
	        if(!(i%alloc)){
	        	c = (float*)realloc(coords,(i/alloc+1)*alloc*3*sizeof(float));
			if(!c){
				WARN("Failed to allocate coordinates array");	
				free(coords);
				free(info);
				return 0;
			}
			else coords = (float*) c;
	        	a = (PMAtomDesc*) realloc(info,(i/alloc+1)*alloc*sizeof(PMAtomDesc));
			if(!c){
				WARN("Failed to allocate info array");	
				free(coords);
				free(info);
				return 0;
			}
			else info = (PMAtomDesc *) a;

			c=&coords[i*3];
			a=&info[i];
		        //fprintf(stderr,">>>>>>%p<<<<<<<\n",coords);
	        }


	        //reading
	        _readLine(linebuffer,a++,c);
	        c+=3;
	        i++;
	    }
		//any line with end stops reading ENDMDL and END
	    else if(!strncmp(linebuffer,"END",3))
	    	break;
	}
	if (*atoms) { //test if size matches
		if(*atoms != i) {
			free(info);
			free(coords);
			return 0;
		}
	}
	else {
		*atoms=i;
	    coords = (float*)   realloc(coords,i*3*sizeof(float));
	    info   = (PMAtomDesc*) realloc(info,i*sizeof(PMAtomDesc));
	}
	*atominfo = info;
	return coords;
}

static float *pmFReadPDBFramePlain(FILE* stream,size_t *atoms)
{
	size_t i=0;
	char linebuffer[128];
	float *coords,*c;

	coords = (float*)malloc(*atoms*3*sizeof(float));
	if(!coords){
		WARN("Failed to allocate coordinates array");	
		free(coords);
		return 0;
	}
	c=coords;

	while(fgets(linebuffer,128,stream)){
		if(i>*atoms){
			free(coords);
			return 0;
		}
		//only atom lines
		if(!strncmp(linebuffer,"ATOM",4) || !strncmp(linebuffer,"HETATM",6)){
			//test line
	        if(strlen(linebuffer)<54)break; // underfull line


	        //reading
	        _readLineS(linebuffer,c);
	        c+=3;
	        i++;
	    }
		//any line with end stops reading ENDMDL and END
	    else if(!strncmp(linebuffer,"END",3))
	    	break;
	}

	if(*atoms != i) { // if not enough atoms
		free(coords);
		return 0;
	}
	return coords;
}


static int pmFWriteFramesPDB(FILE* f, PMAtomDesc* info, float **data,size_t models,size_t atoms)
{
	float *datap,x,y,z;
	size_t i,j;
	char *c;
	PMAtomDesc* inf;

	// Header
	fprintf(f,"REMARK PDB OUTPUT\n"
	    	  "REMARK PDB GENERATED BY PMTK\n"
	          "REMARK PDB FRAMES: %zu\n"
	          "REMARK PDB ATOMS PER FRAME: %zu\n",models,atoms);

	// Data output
    if(info){
    	for(i=0;i<models;i++){
	      fprintf(f,"MODEL   %4zu\n",i);
	      datap=*data;
	      inf=info;
	      for(j=0;j<atoms;j++){
	        x=*datap++;
	        y=*datap++;
	        z=*datap++;
	        c = (char*) &(*inf++);
	        fprintf(f,"%6s%.21s   %8.3f%8.3f%8.3f%6.2f%6.2f\n",
	        (*c=='H')?"HETATM":"ATOM  ",
	        &c[1],
	        x,
	        y,
	        z,
	        0.0,
	        0.0);
	      }
	      data++;
	      fprintf(f,"ENDMDL\n");
	}
	fprintf(f,"END\n");
    }
    else{
    	for(i=0;i<models;i++){
    		fprintf(f,"MODEL   %4zu\n",i);
    		datap=*data;
    		for(j=0;j<atoms;j++){
    		        x=*datap++;
    		        y=*datap++;
    		        z=*datap++;
    		        fprintf(f,"ATOM  %6lu CA               %8.3f%8.3f%8.3f%6.2f%6.2f\n",
    		          j,
    		          x,
    		          y,
    		          z,
    		          0.0,
    		          0.0);
    		}
    		fprintf(f,"ENDMDL\n");
    		data++;
    	}
    	fprintf(f,"END\n");
    }
	fclose(f);
	return 0;
}

PMProteinModel *pdbopen(PMProteinModel *protein,const char * filename, int mode)
{
	FILE *f;
	size_t iatoms;
	PMAtomDesc *info_r;
	PMProteinModel *p=protein;
	float *buffer;

	SAY("Open: %s",filename);
	f = fopen(filename,"r");
	if (!f){
		WARN("Failed open: %s",filename);	
		return 0;
	}
	if(!p)
		p=(PMProteinModel*)pmCreateNew(PM_TYPE_MODEL);
	if(p->type!=PM_TYPE_MODEL){
		WARN("Mixing different representations (abort): %s",filename);
		if(p!=protein) pmDelete((PMProtein*)p);
		return 0;
	}
	iatoms = p->records/3;

	if(!p->desc || p->desc->atoms){
		buffer = pmFReadPDBFrameFull(f,&info_r,&iatoms);
		if(buffer){
			if(mode==1){
				free(buffer);
				if(p->records && p->records!=3*iatoms){
					WARN("Model differs (abort): %s",filename);
				}
				protein->desc = pmCreateAtomDesc(iatoms,info_r);
				p->records=iatoms*3;
			}
			if(!pmAddFrame((PMProtein*)p,buffer,p->records)){
				WARN("Model differs (abort): %s",filename);
				fclose(f);
				if(p!=protein) pmDelete((PMProtein*)p);
				return 0;
			}
			p->desc = pmCreateAtomDesc(iatoms,info_r);
			p->records=iatoms*3;
		}
	}
	while(!feof(f)){
		buffer = pmFReadPDBFramePlain(f,&p->desc->natoms);
		if(buffer)
			if(!pmAddFrame((PMProtein*)p,buffer,p->records)){
				WARN("Model differs (ignored): %s",filename);
			}
	}
	fclose(f);
	return p;
}


PMProteinModel *pdbsave(PMProteinModel *protein,const char * filename, int mode)
{
	FILE *f;
	SAY("Save: %s",filename);
	if(protein->type!=PM_TYPE_MODEL){
		WARN("Mixing different representations (aborted): %s",filename);
		return 0;
	}

        f = fopen(filename,"w");
	pmFWriteFramesPDB(f,protein->desc->atoms,protein->data,protein->frames,protein->records/3);
	fclose(f);
	return protein;
}




